In [13]:
import pandas as pd
import numpy as np
import ast
import json

In [14]:
import os

archivos_en_carpeta = os.listdir()
print(archivos_en_carpeta)

['.ipynb_checkpoints', 'australian_users_items.json', 'australian_user_reviews.json', 'Diccionario de Datos STEAM.xlsx', 'output_steam_games.json', 'Untitled.ipynb', 'Untitled1.ipynb']

In [21]:
allNewLines = []

with open('australian_users_items.json', 'r', encoding='utf-8') as file1:
    contenido = file1.read()
    
    for line in contenido.split('\n'):
        if line.strip():
            NewDict1 = ast.literal_eval(line)
            allNewLines.append(NewDict1)

UserItemsDF = pd.DataFrame(allNewLines)

In [23]:
UserItemsDF.head(2)

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."

In [26]:
allNewLines = []

with open('australian_user_reviews.json', 'r', encoding='utf-8') as file2:
    contenido = file2.read()
    
    for line in contenido.split('\n'):
        if line.strip():
            NewDict2 = ast.literal_eval(line)
            allNewLines.append(NewDict2)

UserReviewsDF = pd.DataFrame(allNewLines)

In [27]:
UserReviewsDF.head(5)

,user_id,user_url,reviews
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2..."
1,js41637,http://steamcommunity.com/id/js41637,"[{'funny': '', 'posted': 'Posted June 24, 2014..."
2,evcentric,http://steamcommunity.com/id/evcentric,"[{'funny': '', 'posted': 'Posted February 3.',..."
3,doctr,http://steamcommunity.com/id/doctr,"[{'funny': '', 'posted': 'Posted October 14, 2..."
4,maplemage,http://steamcommunity.com/id/maplemage,"[{'funny': '3 people found this review funny',..."

In [40]:
all_data = []

with open('output_steam_games.json', 'r', encoding='utf-8') as file3:
    for line in file3:
        try:
            data = json.loads(line)
            all_data.append(data)
        except json.JSONDecodeError as e:
            print(f"Error al decodificar JSON en l√≠nea: {line}")
            print(f"Mensaje de error: {str(e)}")

SteamGamesDF = pd.DataFrame(all_data)

In [43]:
SteamGamesDF2 = pd.DataFrame(all_data)

In [44]:
SteamGamesDF2[SteamGamesDF2.duplicated(keep=False, subset='id')].dropna(subset='id')

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,discount_price,specs,price,early_access,id,metascore,developer,user_id,steam_id,items,items_count
102204,Bethesda Softworks,[Action],Wolfenstein II: The New Colossus,Wolfenstein II: The New Colossus,http://store.steampowered.com/app/612880/,2017-10-26,"[Action, FPS, Gore, Violent, Alternate History...",http://steamcommunity.com/app/612880/reviews/?...,NaN,"[Single-player, Steam Achievements, Full contr...",59.99,False,612880,86,Machine Games,NaN,NaN,NaN,NaN
102883,Bethesda Softworks,[Action],Wolfenstein II: The New Colossus,Wolfenstein II: The New Colossus,http://store.steampowered.com/app/612880/Wolfe...,2017-10-26,"[Action, FPS, Gore, Violent, Alternate History...",http://steamcommunity.com/app/612880/reviews/?...,NaN,"[Single-player, Steam Achievements, Full contr...",59.99,False,612880,86,Machine Games,NaN,NaN,NaN,NaN

In [45]:
index_last_dup_to_remove = SteamGamesDF2[SteamGamesDF2.duplicated(keep='last', subset='id')].dropna(subset='id').index

In [46]:
index_last_dup_to_remove

Int64Index([102204], dtype='int64')

In [47]:
SteamGamesDF2.iloc[index_last_dup_to_remove]

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,discount_price,specs,price,early_access,id,metascore,developer,user_id,steam_id,items,items_count
102204,Bethesda Softworks,[Action],Wolfenstein II: The New Colossus,Wolfenstein II: The New Colossus,http://store.steampowered.com/app/612880/,2017-10-26,"[Action, FPS, Gore, Violent, Alternate History...",http://steamcommunity.com/app/612880/reviews/?...,NaN,"[Single-player, Steam Achievements, Full contr...",59.99,False,612880,86,Machine Games,NaN,NaN,NaN,NaN

In [48]:
SteamGamesDF2.drop(index=index_last_dup_to_remove, inplace=True)

In [51]:
SteamGamesDF2.head(10)

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,discount_price,specs,price,early_access,id,metascore,developer,user_id,steam_id,items,items_count
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76561197970982479,76561197970982479,"[{'item_id': '10', 'item_name': 'Counter-Strik...",277.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,js41637,76561198035864385,"[{'item_id': '10', 'item_name': 'Counter-Strik...",888.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,evcentric,76561198007712555,"[{'item_id': '1200', 'item_name': 'Red Orchest...",137.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Riot-Punch,76561197963445855,"[{'item_id': '10', 'item_name': 'Counter-Strik...",328.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,doctr,76561198002099482,"[{'item_id': '300', 'item_name': 'Day of Defea...",541.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MinxIsBetterThanPotatoes,76561198004744620,"[{'item_id': '50', 'item_name': 'Half-Life: Op...",371.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NitemarePK,76561197990951820,"[{'item_id': '240', 'item_name': 'Counter-Stri...",304.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,themanwich,76561198035296505,"[{'item_id': '220', 'item_name': 'Half-Life 2'...",258.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,maplemage,76561198026584251,"[{'item_id': '240', 'item_name': 'Counter-Stri...",629.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wackky,76561198039117046,[],0.0

In [52]:
SteamGamesDF2.dropna(subset=['id'], inplace=True)

In [53]:
SteamGamesDF2.head(5)

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,discount_price,specs,price,early_access,id,metascore,developer,user_id,steam_id,items,items_count
88310,Kotoshiro,"[Action, Casual, Indie, Simulation, Strategy]",Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,2018-01-04,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,4.49,[Single-player],4.99,False,761140,NaN,Kotoshiro,NaN,NaN,NaN,NaN
88311,"Making Fun, Inc.","[Free to Play, Indie, RPG, Strategy]",Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,2018-01-04,"[Free to Play, Strategy, Indie, RPG, Card Game...",http://steamcommunity.com/app/643980/reviews/?...,NaN,"[Single-player, Multi-player, Online Multi-Pla...",Free To Play,False,643980,NaN,Secret Level SRL,NaN,NaN,NaN,NaN
88312,Poolians.com,"[Casual, Free to Play, Indie, Simulation, Sports]",Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,2017-07-24,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,NaN,"[Single-player, Multi-player, Online Multi-Pla...",Free to Play,False,670290,NaN,Poolians.com,NaN,NaN,NaN,NaN
88313,ÂΩºÂ≤∏È¢ÜÂüü,"[Action, Adventure, Casual]",ÂºπÁÇ∏‰∫∫2222,ÂºπÁÇ∏‰∫∫2222,http://store.steampowered.com/app/767400/2222/,2017-12-07,"[Action, Adventure, Casual]",http://steamcommunity.com/app/767400/reviews/?...,0.83,[Single-player],0.99,False,767400,NaN,ÂΩºÂ≤∏È¢ÜÂüü,NaN,NaN,NaN,NaN
88314,NaN,NaN,Log Challenge,NaN,http://store.steampowered.com/app/773570/Log_C...,NaN,"[Action, Indie, Casual, Sports]",http://steamcommunity.com/app/773570/reviews/?...,1.79,"[Single-player, Full controller support, HTC V...",2.99,False,773570,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
SteamGamesDF2.shape

(32132, 19)

In [57]:
SteamGamesDF2.to_csv('DataSteam2.csv', index=False)